name: My First GitHub Action

on:
  push:
    branches:
      - main

jobs:
  extract-data:
    runs-on: ubuntu-latest
    steps:

      - name: checkout code
        run: actions/checkout@V2

      - name: extracting data 
        run: python extract.py
  transform-data:
    runs-on: ubuntu-latest
    needs: extract-data
    steps:

      - name: checkout code
        run: actions/checkout@V2
        

      - name: transforming data 
        run: python transform.py

  load-data:
    runs-on: ubuntu-latest
    needs: transform-data
    steps:

      - name: checkout code
        run: actions/checkout@V2
        

      - name: loading data 
        run: python load.py