name: Creating Pipeline in ETL

on:
  push:
    branches:
      - main

jobs:
  extract-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python file to extract data
        run: python extract.py

  transform-data:
    runs-on: ubuntu-latest
    needs: extract-data
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Transform data by running Python
        run: python transform.py

  load-data:
    runs-on: ubuntu-latest
    needs: transform-data
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Loading data to destination
        run: python load.py
