name: My First GitHub Action

on:
  push:
    branches:
      - main

jobs:
  extract-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extracting Data
        run: python extract.py

  transform-data:
    runs-on: ubuntu-latest
    needs: extract-data
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Transforming Data
        run: python transform.py

  load-data:
    runs-on: ubuntu-latest
    needs: transform-data
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Loading Data
        run: python load.py
